# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.IntegerField(default=0, help_text='In BDT')),
            ],
            options={
                'ordering': ['reg_number'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('reg_number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('fathers_name', models.CharField(max_length=250)),
                ('mothers_name', models.CharField(max_length=250)),
                ('birthday', models.CharField(help_text='Format : DD/MM/YYYY,Example : 01/01/1960', max_length=250)),
                ('blood_group', models.CharField(help_text='Example : AB+', max_length=20)),
                ('semester', models.CharField(choices=[('1st Semester', '1st'), ('2nd Semester', '2nd'), ('3rd Semester', '3rd'), ('4th Semester', '4th'), ('5th Semester', '5th'), ('6th Semester', '6th'), ('7th Semester', '7th'), ('8th Semester', '8th')], max_length=50)),
                ('session', models.IntegerField(choices=[(2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], default=2017, verbose_name='session')),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.Department')),
            ],
            options={
                'ordering': ['reg_number'],
                'verbose_name': 'Personal Information',
                'verbose_name_plural': 'Personal Infomations',
            },
        ),
        migrations.CreateModel(
            name='RegisteredCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_CGPA', models.CharField(max_length=250)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.Course')),
                ('reg_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.PersonalInfo')),
            ],
            options={
                'ordering': ['reg_number'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_CGPA', models.CharField(max_length=250)),
                ('grade', models.CharField(max_length=250)),
                ('reg_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.PersonalInfo')),
            ],
            options={
                'ordering': ['reg_number'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='reg_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.PersonalInfo'),
        ),
    ]
