# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(default='', max_length=255, verbose_name='email address'),
        ),
    ]
