# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20170305_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='reg_number',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
