# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_personalinfo_secret_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='secret_key',
            new_name='TrxID',
        ),
    ]
