# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20170521_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='TrxID',
            new_name='password',
        ),
    ]
