# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20170521_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='password',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='TrxID',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Password'),
        ),
    ]
