# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
        ('students', '0008_auto_20170521_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField(auto_now=True)),
                ('is_attend', models.BooleanField(default=False)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.Course')),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.Department')),
            ],
            options={
                'ordering': ['-class_date'],
            },
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='student_image',
            field=models.ImageField(default='', height_field='height_field', upload_to=students.models.upoload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='semster',
            field=models.CharField(choices=[('1st Semester', '1st'), ('2nd Semester', '2nd'), ('3rd Semester', '3rd'), ('4th Semester', '4th'), ('5th Semester', '5th'), ('6th Semester', '6th'), ('7th Semester', '7th'), ('8th Semester', '8th')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='attendence',
            name='reg_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.PersonalInfo'),
        ),
    ]
