# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20170521_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='height_field',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='width_field',
            field=models.IntegerField(default=100),
        ),
    ]
