# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
        ('students', '0011_auto_20170521_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(auto_now=True)),
                ('total_marks', models.CharField(default='20', max_length=20)),
                ('obtain_marks', models.CharField(default='Absent', max_length=20)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.Course')),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.Department')),
                ('reg_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.PersonalInfo')),
            ],
            options={
                'ordering': ['-exam_date'],
            },
        ),
    ]
