# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='exam_time',
            field=models.CharField(default='', help_text='Example: CSE-101:10 AM,CSE-102:11 AM', max_length=250),
        ),
    ]
