# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 18:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator(code='invalid username', message='Username must be Alphanumeric and contain any of the following : ". @ + - "', regex='^[a-zA-Z0-9.@+-]*$')])),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('reg_number', models.CharField(max_length=250, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
