# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 18:37
from __future__ import unicode_literals

import Academic.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(default='', max_length=250, primary_key=True, serialize=False, unique=True)),
                ('course_title', models.CharField(default='', max_length=250)),
                ('credit', models.CharField(default='', max_length=20)),
                ('semester', models.CharField(choices=[('1st Semester', '1st'), ('2nd Semester', '2nd'), ('3rd Semester', '3rd'), ('4th Semester', '4th'), ('5th Semester', '5th'), ('6th Semester', '6th'), ('7th Semester', '7th'), ('8th Semester', '8th')], default='', max_length=250)),
                ('ref_book', models.FileField(default='', upload_to='')),
                ('course_image', models.ImageField(default='', height_field='height_field', upload_to=Academic.models.upoload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('course_description', models.TextField(default='')),
                ('course_detail', models.TextField(default='')),
                ('course_fees', models.CharField(default='', max_length=250)),
                ('course_teacher', models.TextField(default='')),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('short_name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('course_file', models.FileField(default='', upload_to='')),
            ],
            options={
                'ordering': ['dept_name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.Department'),
        ),
    ]
