# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_personalinformation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='active_research_project',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='awards_and_recognition',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='biography',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='conference_proceedings',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='external_affiliations',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='graduate_supervision',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='previous_research_project',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='research_interests',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='selected_publications',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='teaching',
            field=models.TextField(default=''),
        ),
    ]
