# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_remindermodel_dept_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendencemodel',
            name='email',
            field=models.EmailField(default='', max_length=255, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='remindermodel',
            name='email',
            field=models.EmailField(default='', max_length=255, verbose_name='email address'),
        ),
    ]
